server:
  port: 8094
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  profiles:
    default: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB